name: Create a PR
description: This action creates a new branch, commits current changes and creates a PR.
inputs:
  branch:
    description: The branch to create and open a PR for.
    required: true
  commit_message:
    description: The commit message.
    required: true
  title:
    description: The PR's title.
    required: true
  body:
    description: The PR's body.
    required: true
  token:
    description: The GitHub token.
    required: true
  assignees:
    description: The assignees, in a comma separated list. For example "user01, user02, user03".
outputs:
  url:
    description: The URL of the pull request
    value: ${{ steps.url.outputs.url }}
runs:
  using: "composite"
  steps:
    - run: git config --global user.name "${{ github.actor }}"
      shell: bash
    - run: git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      shell: bash
    - run: git checkout -b "${{ inputs.branch }}"
      shell: bash
    - run: git add .
      shell: bash
    - run: git commit -m "${{ inputs.commit_message }}"
      shell: bash
    - run: git push origin "${{ inputs.branch }}" --force
      shell: bash
    - name: Format Assignees Argument
      shell: bash
      id: assignees
      if: ${{ inputs.assignees }}
      run: echo "arg=--assignee $(echo "${{ inputs.assignees }}" | tr -d ' ')" >> $GITHUB_OUTPUT
    - name: print args
      shell: bash
      run: echo "$assignee arg is '{{ steps.assignees.outputs.arg }}'"
    - run: gh pr create --title "${{ inputs.title }}" --body "${{ inputs.body }}" ${{ steps.assignees.outputs.arg }} > url.txt
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - run: cat url.txt
      shell: bash
    - run: echo "url=$(cat url.txt)" >> $GITHUB_OUTPUT
      id: url
      shell: bash
