name: Create Release PR
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The released version without 'v'. For example, 1.0.0.

env:
  # todo: use the one for buf
  APP_ID: 417207

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ secrets.TOKEN_EXCHANGE_GH_APP_PRIVATE_KEY }}
      - name: Update Version and Changelog and Create PR
        run: bash ./make/buf/scripts/releasechangelogandversion.bash
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          VERSION: ${{ github.event.inputs.version }}
          # WEBHOOK_URL: ...
      # placeholder for slack notification